### ISSUE TITLE
Deck Not Found

### ISSUE THREAD

**Issue by Frainlar** [Sri-nidhi/airflow2.0-demo#3]
The Slide Deck mentioned in README.md looks like a dead link. Please provide the link to your Deck "Getting started with Apache Airflow". 
![image](https://user-images.githubusercontent.com/17977883/122206246-c2aa9780-cebe-11eb-982d-65d8d775de52.png)

**Comment by Sri-nidhi** [comment]
@Frainlar Thanks for highlighting it, the link should work now.
